#!/bin/bash

# Check if the argument is provided
if [ $# -eq 0 ]; then
	echo "Usage: $0 <file_path>"
	exit 1
fi

file_path="$1"

export CONFLUENCE_FILE_PATH="$file_path"

output=$(node /home/abdelmounim/projects/confluence-api/index.js)

echo "$output"
